"""
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

Example:
Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""

class Solution:
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        dict = {}
        for char in s:
            if char not in dict:
                dict[char] = 1
            else:
                dict[char] += 1

        for char in t:
            if char not in dict:
                dict[char] = 1
            else:
                dict[char] += 1

        for key,val in dict.items():
            if val%2 == 1:
                return key

    def findTheDifference2(self,s,t):
        ans = 0
        for char in s + t:
            ans ^= ord(char)
        return chr(ans)

    def findTheDifference3(self,s,t):
        dic = {}
        # get the value in dict, if not found return 0
        for ch in s:
            dic[ch] = dic.get(ch, 0) + 1
        for ch in t:
            if dic.get(ch, 0) == 0:
                return ch
            else:
                dic[ch] -= 1

s = "abcd"
t = "abcde"
print(Solution().findTheDifference3(s,t))